# Generated by Django 4.2.5 on 2023-11-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_aichat_datetime_alter_userchat_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('is_AI', models.BooleanField(default=False, help_text='AIの回答ならTrue')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='room',
        ),
        migrations.DeleteModel(
            name='AIChat',
        ),
        migrations.DeleteModel(
            name='UserChat',
        ),
    ]
