name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    # IP取得ライブラリをインストール
    - name: Public IP Install
      id: ip
      uses: haythem/public-ip@v1.2
    # BranchをCheckout
    - uses: actions/checkout@v3
    # Pythonのバージョン設定
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # デプロイする
    - name: Deploy
      run: |
        # SSH接続して、git pullする
        echo "${{ secrets.PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -oStrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key "cd chatzeus \
        && git fetch \
        && git merge --no-edit \
        && source /home/ec2-user/.cache/pypoetry/virtualenvs/chatzeus-KwToeiZz-py3.11/bin/activate \
        && poetry install \
        && python manage.py makemigrations \
        && python manage.py migrate \
        && python manage.py collectstatic --noinput \
        && deactivate \
        && sudo systemctl restart gunicorn"
        

